/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Z1DrawingPanel.java
 *
 * Created on 2010-01-17, 11:58:16
 */

package GUI;

import Logic.zad1.Perceptron;
import Logic.zad1.PrzykladUczacy;
import java.awt.Color;
import java.awt.Graphics;
import java.util.Vector;

/**
 *
 * @author Pawel
 */
public class Z1DrawingPanel extends javax.swing.JPanel {

    /** Creates new form Z1DrawingPanel */

    Vector<PrzykladUczacy> przyklady = null;
    Perceptron p = null;

    public Z1DrawingPanel() {
        initComponents();
    }

    public void drawExamples(Graphics g) {
        for (PrzykladUczacy e : przyklady) {
            if (e.getResult() == 1) {
                g.setColor(Color.GREEN);
            } else if (e.getResult() == -1) {
                g.setColor(Color.RED);
            }
            double x = e.getVal()[0];
            double y = e.getVal()[1];
            g.fillRect((int) x, (int) y, 2, 2);
        }
    }

    public void drawFunction(Graphics g) {
        double pp = this.p.getProg();
        double w1 = this.p.getWagi()[0];
        double w2 = this.p.getWagi()[1];
        double mod = Math.sqrt(w1 * w1 + w2 * w2);
        double d = -pp / mod;
        double a = w2 / w1;
        double x = d / Math.sqrt(1 + a * a);
        double y = a * x;
        double aprim = -1 / a;
        double bprim = y - aprim * x;
        double x1 = -1000.0;
        double x2 = 1000.0;
        double y1 = aprim * x1 + bprim;
        double y2 = aprim * x2 + bprim;
        g.setColor(Color.BLACK);
        g.drawLine((int) x1, (int) y1, (int) x2, (int) y2);
    }

    public void setPrzyklady(Vector<PrzykladUczacy> ex) {
        przyklady = ex;
    }

    public void setPerceptron(Perceptron p) {
        this.p = p;
    }


    @Override
    public void paint(Graphics g) {
        super.paint(g);
        if (przyklady!=null && p!=null) {
            drawExamples(g);
            drawFunction(g);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
